# site
title: Fry
baseurl: "/fry"
url: "http://lillian-chen.com"
favicon: "/assets/ico.png"
g_analytics: UA-12345678-1

# bio
header: Fry
desc: >
  Fry is <a href="https://github.com/lllychen/louie" target="_blank">Louie</a>'s
  much more graphic-heavy, photogenic brother (still a Jekyll theme tho).

# posts
date_format: "%Y"

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock